### ISSUE TITLE
Potlasok

### ISSUE THREAD

**Issue by hegyhati** [Uni-Sopron/dtr-o21-beadando-mikulas#1]
- [x] kicsit bovebb leiras, hogy mi  a peldabemenet, kimenetet megmutatni, mindez md-ben, ne pdf
- [x] futtatni tobb bemenetre, megnezni pl hogy valtozik-e a helyzet, ha valaki elkoltozik, vagy ilyesmi
- [x] masodik valtozatot kipofozni

**Comment by KissKlaudia99** [comment]
A második változathoz szeretnék segítséget kérni, ha ez lehetséges. A tömbök felvételénél akadtam el.
Az első két pontot megcsináltam, feltöltöttem.

**Comment by hegyhati** [comment]
Mielott a masodik valtozatra raterunk, az elso valtozathoz: na pont ilyenkor mar ugye illik az, hogy egy modell fajl van, es 3 data file., es akkor a modell nincs meg redundansan 3 fajlban, csak egy helyen.

A masodikhoz: ha jol ertem, ez segit, de ha rosszul ertettem, hol akadtal el, akkor szolj: 

```ampl
set fesztivalok;
set bandak;
set fellepesek{bandak} within fesztivalok;

var x{fesztivalok} binary;

s.t. mindenkit_egyszer{b in bandak}:
    sum {f in fellepesek[b]} x[f] >= 1;

minimize osszes: sum{f in fesztivalok} x[f];

data;

set fesztivalok := f1 f2 f3;
set bandak := b1 b2;
set fellepesek[b1] := f1 f2;
set fellepesek[b2] := f2 f3;
```

**Comment by KissKlaudia99** [comment]
Ez alapján az adatokat már fel tudtam venni, viszont a logikában még mindig van hibám, és nem jövök rá, hogy mi az. Feltöltöttem a Mikulas2.mod fájlt, amiben látszik, hogy mire jutottam.

**Comment by hegyhati** [comment]
Az `ottlakik` az nem tunik nekem valtozonak, ha a bemeneti adatokbol kulonbozik. Illetve azt mondod, hogy "adott utcaban", de nins utca argumentuma.

De nem is latom, hogy mire kellene. A 4. korlatozas:
```ampl
minden utcara, minden jatkra, a gyerekek kozul akik ott laknak csak legfeljebb egy kaphatja meg
u in utcak     j in jatekok     : a gyerekek kozul akik BenneLakik[u]-ban vannak, legfeljebb egy kaphatja meg
u in utcak     j in jatekok     : sum{g in BenneLakik[u]} megkapja[g,j] <= 1
 ```

Innet szerintem mar menni fog :-)

**Comment by KissKlaudia99** [comment]
Köszönöm szépen a segítséget. A megoldást feltöltöttem.

**Comment by hegyhati** [comment]
Szuper, meg annyit tegyel meg kerlek, hogy a model1-nel a 3 modell helyett legyen 1 model, meg 3 dat, ha meg van kedved kettot utni rajta, de reszemrol issue lezarva, jo allamvizsga keszulest :-)
